hooks
style
	^ '.center { text-align: center; }
	*{font-family: Verdana;color:#212121}
	
	.boton {border-radius: 10px; border: 2px solid #5c6bc0;padding: 10px 16px;background-color:#fafafa}
	.boton:hover {border: 2px solid #26418f;  background-color:#eceff1}
	
	.link{ text-decoration:none; color:#212121}
	.link:hover{color:#5c6bc0}
	
	.list{list-style: none; margin:0px; padding:0px;}
	.list-item{padding:10px; text-decoration:none; color:#212121 }
	
	
	.colum1{width: 25%;float: left; text-align: center; }
	.colum2{width: 40% ;float: left; text-align: center;  }
	.colum3{width: 20% ;float: left; text-align: center; }
	.colum4{width: 15% ;float: left; text-align: center;margin-bottom:2em; }

	
	.table-item{border: 1px solid #171717}
	
	.homeColum{width: 50%; float: left;text-align: center; }
	'